version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "nielsmadan"
    groups:
      non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
